# Generated by Django 2.1.7 on 2019-05-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_content', models.CharField(blank=True, max_length=500)),
                ('first_title', models.CharField(blank=True, max_length=100)),
                ('first_content', models.TextField(blank=True)),
                ('first_image', models.ImageField(blank=True, default=None, upload_to='')),
                ('second_title', models.CharField(blank=True, max_length=100)),
                ('second_content', models.TextField(blank=True)),
                ('second_image', models.ImageField(blank=True, default=None, upload_to='')),
                ('third_title', models.CharField(blank=True, max_length=500)),
                ('third_content', models.TextField(blank=True)),
                ('third_image', models.ImageField(blank=True, default=None, upload_to='')),
                ('fourth_title', models.CharField(blank=True, max_length=100)),
                ('fourth_content', models.TextField(blank=True)),
                ('fourt_image', models.ImageField(blank=True, default=None, upload_to='')),
                ('fith_title', models.CharField(blank=True, max_length=100)),
                ('fith_content', models.TextField(blank=True)),
                ('fifth_image', models.ImageField(blank=True, default=None, upload_to='')),
                ('six_title', models.CharField(blank=True, max_length=500)),
                ('six_content', models.TextField(blank=True)),
                ('seven_title', models.CharField(blank=True, max_length=500)),
                ('seven_content', models.TextField(blank=True)),
                ('eight_title', models.CharField(blank=True, max_length=500)),
                ('eight_content', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_lottery', models.CharField(max_length=100)),
                ('jackpot', models.CharField(max_length=40)),
                ('odds', models.CharField(max_length=100)),
                ('dragnings_datum', models.CharField(max_length=400)),
                ('price_range', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, default=None, upload_to='')),
                ('flaga', models.ImageField(blank=True, default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_lottery', models.CharField(max_length=100)),
                ('amount_they_won', models.CharField(blank=True, max_length=400)),
                ('first_title', models.CharField(blank=True, max_length=500)),
                ('first_content', models.TextField(blank=True)),
                ('second_title', models.CharField(blank=True, max_length=500)),
                ('second_content', models.TextField(blank=True)),
                ('third_title', models.CharField(blank=True, max_length=500)),
                ('third_content', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Article')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery'),
        ),
    ]
