# Generated by Django 2.2 on 2019-07-03 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mini_lottery_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_lottery', models.CharField(blank=True, max_length=100)),
                ('mini_logo', models.ImageField(blank=True, default=None, upload_to='')),
                ('mini_content', models.CharField(blank=True, max_length=100)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery')),
            ],
        ),
    ]
