# Generated by Django 2.2 on 2019-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_adress', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='lottery',
            name='mini_content',
            field=models.TextField(blank=True),
        ),
    ]
