# Generated by Django 2.1.7 on 2019-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='intro_content',
        ),
        migrations.AddField(
            model_name='lottery',
            name='intro_content',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
