# Generated by Django 2.1.7 on 2019-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_lottery', models.CharField(blank=True, max_length=100)),
                ('winning_amount', models.CharField(blank=True, max_length=100)),
                ('dragnings_datum', models.CharField(blank=True, max_length=100)),
                ('odds', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('flaga', models.ImageField(blank=True, default=None, upload_to='')),
            ],
        ),
    ]
