# Generated by Django 2.2 on 2019-07-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabell',
        ),
    ]
