# Generated by Django 2.2 on 2019-07-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2019-07-01 18:00:15.582775'),
            preserve_default=False,
        ),
    ]
