# Generated by Django 2.2 on 2019-07-27 16:20

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('profil_bild', models.ImageField(blank=True, default=None, upload_to='')),
                ('welcome_title', models.CharField(blank=True, max_length=100)),
                ('welcome_text', models.TextField(blank=True)),
                ('content', django_bleach.models.BleachField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
