# Generated by Django 2.2 on 2019-07-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customer_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
