# Generated by Django 2.1.7 on 2019-06-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_first_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_page',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
