# Generated by Django 2.1.7 on 2019-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_best_lottery'),
    ]

    operations = [
        migrations.AddField(
            model_name='best_lottery',
            name='content',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
