# Generated by Django 2.2 on 2019-07-01 08:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_tabell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='d_content',
        ),
        migrations.AddField(
            model_name='lottery',
            name='project_code',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Code'),
        ),
    ]
