# Generated by Django 2.2 on 2019-07-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_mini_lottery_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='efter_name',
            new_name='efternamn',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='namn',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='telefonnummer',
        ),
        migrations.AddField(
            model_name='customer',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
