# Generated by Django 2.2 on 2019-06-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190629_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('a_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('a_Matchningar', models.CharField(blank=True, max_length=100)),
                ('b_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('b_Matchningar', models.CharField(blank=True, max_length=100)),
                ('b_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('c_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('c_Matchningar', models.CharField(blank=True, max_length=100)),
                ('c_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('d_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('d_Matchningar', models.CharField(blank=True, max_length=100)),
                ('d_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('e_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('e_Matchningar', models.CharField(blank=True, max_length=100)),
                ('e_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('f_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('f_Matchningar', models.CharField(blank=True, max_length=100)),
                ('f_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('g_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('g_Matchningar', models.CharField(blank=True, max_length=100)),
                ('g_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('h_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('h_Matchningar', models.CharField(blank=True, max_length=100)),
                ('h_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('k_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('k_Matchningar', models.CharField(blank=True, max_length=100)),
                ('k_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('l_Vinstnivå', models.CharField(blank=True, max_length=100)),
                ('l_Matchningar', models.CharField(blank=True, max_length=100)),
                ('l_vinnarodds', models.CharField(blank=True, max_length=100)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery')),
            ],
        ),
    ]
