# Generated by Django 2.1.7 on 2019-05-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_best_lottery_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_lottery',
            name='content',
            field=models.TextField(max_length=400),
        ),
    ]
