# Generated by Django 2.1.7 on 2019-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190607_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='price_range',
        ),
        migrations.AddField(
            model_name='lottery',
            name='continent',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
