# Generated by Django 2.2 on 2019-06-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tabell'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='l_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='l_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='jackpot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='odds',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='pris_biljett',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
