# Generated by Django 2.2 on 2019-08-06 14:47

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190727_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='a_content',
            new_name='meta_description',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='a_title',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='b_content',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='b_image',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='b_title',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='c_content',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='c_title',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='d_content',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='d_title',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='e_content',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='e_title',
        ),
        migrations.AddField(
            model_name='winner',
            name='content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
