# Generated by Django 2.2 on 2019-07-01 10:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190701_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='project_code',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
