# Generated by Django 2.1.7 on 2019-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190528_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='best_lottery',
            name='logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
