# Generated by Django 2.2.3 on 2019-08-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190806_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topp_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery')),
            ],
        ),
    ]
