# Generated by Django 2.1.7 on 2019-06-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190531_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='fourt_image',
            new_name='fourth_image',
        ),
    ]
