# Generated by Django 2.2 on 2019-07-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190705_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_1', models.CharField(blank=True, max_length=200)),
                ('article_2', models.CharField(blank=True, max_length=200)),
                ('article_3', models.CharField(blank=True, max_length=200)),
                ('article_4', models.CharField(blank=True, max_length=200)),
                ('article_5', models.CharField(blank=True, max_length=200)),
                ('article_6', models.CharField(blank=True, max_length=200)),
                ('article_7', models.CharField(blank=True, max_length=200)),
                ('article_8', models.CharField(blank=True, max_length=200)),
                ('article_9', models.CharField(blank=True, max_length=200)),
                ('article_10', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lottery_supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, default=None, upload_to='')),
                ('content_box_1', models.TextField(blank=True)),
                ('content_box_2', models.TextField(blank=True)),
                ('content_box_3', models.TextField(blank=True)),
                ('content_box_4', models.TextField(blank=True)),
                ('content_box_5', models.TextField(blank=True)),
                ('content_box_6', models.TextField(blank=True)),
                ('Lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery')),
            ],
        ),
    ]
