# Generated by Django 2.2 on 2019-08-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_topp_10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='b_image',
            new_name='supplier_logo',
        ),
        migrations.RenameField(
            model_name='topp_10',
            old_name='Lottery',
            new_name='lottery',
        ),
        migrations.AlterField(
            model_name='lottery',
            name='intro_content',
            field=models.TextField(blank=True, max_length=550),
        ),
    ]
