# Generated by Django 2.1.7 on 2019-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_best_lottery_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_lottery', models.CharField(max_length=100)),
                ('first_content', models.TextField(blank=True)),
                ('first_title', models.CharField(blank=True, max_length=500)),
                ('second_content', models.TextField(blank=True)),
                ('third_title', models.CharField(blank=True, max_length=500)),
                ('third_content', models.TextField(blank=True)),
                ('right_side_content_first', models.CharField(blank=True, max_length=100)),
                ('right_side_content_second', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='winner',
            name='first_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='winner',
            name='lottery',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='winner',
            name='second_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='winner',
            name='third_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
