# Generated by Django 2.1.7 on 2019-06-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190601_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rektangel', models.ImageField(blank=True, default=None, upload_to='')),
                ('kvadrat', models.ImageField(blank=True, default=None, upload_to='')),
                ('spare', models.ImageField(blank=True, default=None, upload_to='')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery')),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='eight_content',
            new_name='eigth_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='fifth_image',
            new_name='eigth_image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='eight_title',
            new_name='eigth_title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='first_image',
            new_name='image_left',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='third_image',
            new_name='image_right',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='seven_content',
            new_name='nith_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='seven_title',
            new_name='nith_title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='six_content',
            new_name='seventh_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='six_title',
            new_name='seventh_title',
        ),
        migrations.AddField(
            model_name='article',
            name='sixth_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sixth_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='tenth_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tenth_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
