# Generated by Django 2.2 on 2019-07-01 11:38

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190701_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='j_content',
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='k_content',
        ),
        migrations.AddField(
            model_name='lottery',
            name='d_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='j_content_with_list',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='k_content_with_list',
            field=django_bleach.models.BleachField(blank=True),
        ),
    ]
