# Generated by Django 2.2 on 2019-07-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190707_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery_supplier',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='lottery_supplier',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='lottery_supplier',
            name='link_3',
        ),
        migrations.AddField(
            model_name='lottery_supplier',
            name='content_box_4',
            field=models.TextField(blank=True),
        ),
    ]
