# Generated by Django 2.2 on 2019-08-21 19:39

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190821_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='supplier_banner',
            field=django_bleach.models.BleachField(blank=True),
        ),
    ]
