# Generated by Django 2.1.7 on 2019-05-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190528_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='best_lottery',
            name='lottery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Lottery'),
            preserve_default=False,
        ),
    ]
