# Generated by Django 2.1.7 on 2019-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_best_lottery_lottery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='first_title',
        ),
        migrations.AddField(
            model_name='lottery',
            name='second_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='right_side_content_first',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='right_side_content_second',
            field=models.TextField(blank=True),
        ),
    ]
