# Generated by Django 2.2 on 2019-07-10 07:43

from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190708_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery_supplier',
            name='namn',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Meta_tags_for_lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', django_bleach.models.BleachField(blank=True)),
                ('meta_description', django_bleach.models.BleachField(blank=True)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery')),
            ],
        ),
    ]
