# Generated by Django 2.2 on 2019-07-01 11:46

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190701_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='j_content_with_list',
            new_name='j_content',
        ),
        migrations.RenameField(
            model_name='lottery',
            old_name='k_content_with_list',
            new_name='k_content',
        ),
        migrations.AlterField(
            model_name='lottery',
            name='a_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='b_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='c_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='e_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='f_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='g_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='h_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='i_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='l_content',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='welcome_text',
            field=django_bleach.models.BleachField(blank=True),
        ),
    ]
