# Generated by Django 2.1.7 on 2019-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190601_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_image_left',
            new_name='a_content_image_right',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='below_big_content',
            new_name='a_first_small_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='first_small_content',
            new_name='a_second_small_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='second_small_content',
            new_name='a_top_big_content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content_image_right',
            new_name='b_content_image_left',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='top_big_content',
            new_name='b_first_small_content',
        ),
        migrations.AddField(
            model_name='article',
            name='a_first_small_title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='a_first_title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='a_second_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='b_first_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='b_second_small_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='b_second_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='b_second_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='b_top_big_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='c_content_image_right',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='c_down_big_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='c_first_small_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='c_first_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='c_second_small_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='c_second_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='c_second_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='d_content_image_left',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='d_down_big_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='d_first_small_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='d_first_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='d_second_small_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='d_second_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='d_second_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
