# Generated by Django 2.2 on 2019-07-10 09:31

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190710_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery_supplier',
            name='Lottery',
        ),
        migrations.RemoveField(
            model_name='lottery_supplier',
            name='slug',
        ),
        migrations.AlterField(
            model_name='lottery_supplier',
            name='content_box_4',
            field=django_bleach.models.BleachField(blank=True),
        ),
    ]
