# Generated by Django 2.1.7 on 2019-06-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190601_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='first_content',
            new_name='a_first_small_content',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='second_content',
            new_name='a_top_big_content',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='third_content',
            new_name='b_first_small_content',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='first_title',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='name_of_lottery',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='second_title',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='third_title',
        ),
        migrations.AddField(
            model_name='winner',
            name='a_first_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='winner',
            name='b_first_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='winner',
            name='b_top_big_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='bild',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='winner',
            name='welcome_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='welcome_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='a_first_small_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='a_first_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
