# Generated by Django 2.1.7 on 2019-05-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190528_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winning_amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_amount', models.CharField(max_length=400)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery')),
            ],
        ),
        migrations.AddField(
            model_name='winner',
            name='amount_they_won',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='winner',
            name='name_of_lottery',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='best_lottery',
            name='winning_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Winning_amount'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Lottery'),
        ),
    ]
