# Generated by Django 2.2 on 2019-07-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190710_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_links',
            name='article_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_10',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_6',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_7',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_8',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='article_links',
            name='article_9',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
