# Generated by Django 2.1.7 on 2019-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190601_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='a_top_big_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='winner',
            name='b_top_big_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
