# Generated by Django 2.1.7 on 2019-05-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190530_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winning_amount',
            name='lottery',
        ),
        migrations.RenameField(
            model_name='lottery',
            old_name='right_side_content_first',
            new_name='eight_content',
        ),
        migrations.RenameField(
            model_name='lottery',
            old_name='right_side_content_second',
            new_name='fith_content',
        ),
        migrations.AddField(
            model_name='lottery',
            name='eight_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lottery',
            name='first_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lottery',
            name='fith_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lottery',
            name='fourth_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='fourth_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lottery',
            name='pot_amount',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='lottery',
            name='seven_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='seven_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lottery',
            name='six_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lottery',
            name='six_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='best_lottery',
            name='winning_amount',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.DeleteModel(
            name='Winning_amount',
        ),
    ]
