# Generated by Django 2.2 on 2019-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190711_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_links',
            name='label_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_10',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_6',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_7',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_8',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article_links',
            name='label_9',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
