# Generated by Django 2.2 on 2019-07-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190713_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_tags_for_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Winner')),
            ],
        ),
    ]
