# Generated by Django 2.2 on 2019-07-13 10:41

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_meta_tags_for_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_tags_for_winner',
            name='meta_description',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='meta_tags_for_winner',
            name='meta_title',
            field=django_bleach.models.BleachField(blank=True),
        ),
    ]
