# Generated by Django 2.2 on 2019-07-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190713_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_tags_for_lottery',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meta_tags_for_lottery',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meta_tags_for_winner',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
    ]
