# Generated by Django 2.2 on 2019-07-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20190713_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Lottery_supplier'),
            preserve_default=False,
        ),
    ]
